"""empty message

Revision ID: 5914d1605f46
Revises: a6f1cf2ad73d
Create Date: 2021-08-05 18:43:28.737237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5914d1605f46'
down_revision = 'a6f1cf2ad73d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('console',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('release_date', sa.DateTime(), nullable=True),
    sa.Column('price', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('company', sa.String(length=150), nullable=True),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('console')
    # ### end Alembic commands ###
